# Generated by Django 4.1.4 on 2022-12-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_scope_article_alter_scope_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='scope',
            new_name='tag',
        ),
    ]
